# See syntax at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# When updating/renaming this file, also update the `GitHubFeedbackManager` class in the main repo.

name: 🐞 Bug report
description: File a bug report to improve the game
title: '<Brief bug description>'
type: Bug
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please search through our existing [bugs](https://github.com/DerploidEntertainment/HighHandHoldem-Support/issues?q=is%3Aissue%20%20type%3ABug) to see if someone else has already reported this bug.
        > If so, please just like that Issue, rather than opening a new one. 🙏

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: Description
      placeholder: |
        **Do not enter your name, email, phone, or any other personally identifiable information!**

        ## Steps to reproduce

        1. Go to screen '...'
        2. Start a match
        3. Press hand '....'
        4. See error

        ## Expected behavior
        Clear and concise description of what you _expected_ to happen.

        ## Actual behavior
        Clear and concise description of what _actually_ happened.

        ## Additional information
        Any other context about the problem, including screenshots.

  - id: game-version
    type: input
    validations:
      required: true
    attributes:
      label: Game version
      description: Version of the game running on your device (found on the About screen).
      placeholder: "'1.1.0 (#123)' or 'Unknown'"

  - id: device-os
    type: input
    validations:
      required: true
    attributes:
      label: Device operating system
      description: Find in device settings (usually under "General" or "About").
      placeholder: "'iOS 18.1' or 'Android 13' or 'Unknown'"

  - id: device-model
    type: input
    validations:
      required: true
    attributes:
      label: Device model
      description: Find in device settings (usually under "General" or "About").
      placeholder: "'iPhone6.1' or 'SAMSUNG-SM-G900A' or 'Unknown'"

  - id: graphics-device-version
    type: input
    validations:
      required: false
    attributes:
      label: Graphics device version
      description: Find in device settings
      placeholder: OpenGL 2.0
