blank_issues_enabled: false
contact_links:
  - name: General support
    url: 'mailto:support@derploid.com'
    about: Use this email for general support questions, or to include personally identifiable information (like name or phone number) in your question.
