name: Feature request
description: 💡 Suggest an idea for the game
title: 'Add <feature>'
labels: [ enhancement ]
assignees: []
body:
  - id: is-problem
    type: textarea
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is, or "N/A".
      placeholder: I'm always frustrated when ...

  - id: problem-solution
    type: textarea
    attributes:
      label: If so, describe the solution you'd like
      description: A clear and concise description of what you want to happen, and any alternative solutions or features you've considered.

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: What would you like us to add?
      description: A clear and concise description of what you'd like to see added to the game, or "N/A" if you already filled out the above fields.

  - id: notes
    type: textarea
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request.
