# See syntax at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# When updating/renaming this file, also update the `GitHubFeedbackManager` class in the main repo.

name: 🤔 Question
description: Ask a question about the game
title: 'Question about <topic>'
#type: none really applies here
labels: [ question ]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please search through our existing [Issues](https://github.com/DerploidEntertainment/HighHandHoldem-Support/issues?q=is%3Aissue) to see if someone else has already asked your question.
        > If so, please just like that Issue, rather than opening a new one. 🙏

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: Question about gameplay
      description: >
        A clear and concise question about some specific aspect of gameplay, a non-gameplay screen, or anything else.
        Please provide all necessary context or screenshots to help us understand your question.
      placeholder: |
        **Do not enter your name, email, phone, or any other personally identifiable information!**

        E.g., "How do I select a hand?"

  - id: game-version
    type: input
    validations:
      required: true
    attributes:
      label: Game version
      description: Version of the game running on your device (found on the About screen).
      placeholder: "'1.1.0 (#123)' or 'Unknown'"

  - id: device-os
    type: input
    validations:
      required: true
    attributes:
      label: Device operating system
      description: Find in device settings (usually under "General" or "About").
      placeholder: "'iOS 18.1' or 'Android 13' or 'Unknown'"

  - id: device-model
    type: input
    validations:
      required: true
    attributes:
      label: Device model
      description: Find in device settings (usually under "General" or "About").
      placeholder: "'iPhone6.1' or 'SAMSUNG-SM-G900A' or 'Unknown'"

  - id: graphics-device-version
    type: input
    validations:
      required: false
    attributes:
      label: Graphics device version
      description: Find in device settings
      placeholder: OpenGL 2.0
