name: 🤔 Question
description: Ask a question about the game
title: 'Question about <topic>'
labels: [ question ]
assignees: []
body:
  - id: is-gameplay
    type: textarea
    validations:
      required: true
    attributes:
      label: Question about gameplay
      description: A clear and concise question about some specific aspect of gameplay, or "N/A" if your question is about something else.
      placeholder: E.g., how do I select a hand?

  - id: is-non-gameplay
    type: textarea
    validations:
      required: true
    attributes:
      label: Question about a non-gameplay screen
      description: A clear and concise question about a non-gameplay screen, or "N/A" if your question is about something else.
      placeholder: E.g., how do I close the Pause screen?

  - id: question
    type: textarea
    validations:
      required: true
    attributes:
      label: Question about anything
      description: A clear and concise question, or "N/A" if you already filled out one of the above fields.
      placeholder: E.g., what are your programmer's favorite pizza toppings?

  - id: notes
    type: textarea
    attributes:
      label: Additional context
      description: Any other context or screenshots about your question.
